// import { Geist, Geist_Mono } from "next/font/google";
import {JetBrains_Mono} from 'next/font/google'
import "./globals.css";
import Header from '@/components/Header';
import PageTransition from '@/components/PageTransition';
import StairTransition from '@/components/StairTransition';


const jetBrainsMono = JetBrains_Mono({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700', '800']
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jetBrainsMono.className}`}>
      <body
        className='antialiased'
      >
        <Header />
        <StairTransition />
        <PageTransition>
          {children}
        </PageTransition>

      </body>
    </html>
  );
}
